name: 'DeploySlim'
description: 'Compress web assets (HTML, CSS, JS, etc.) with Brotli & Gzip in GitHub Actions. Works on Linux/Windows.'
author: 'CornerstoneCode'

inputs:
  directory:
    description: 'The directory containing the web assets to compress.'
    required: false
    default: '.'
  algorithms:
    description: 'Comma-separated list of compression algorithms (br, gz). Default: br,gz'
    required: false
    default: 'br,gz'
  brotli-level:
    description: 'Brotli compression level (0-11). Default: 6'
    required: false
    default: '6'
  gzip-level:
    description: 'Gzip compression level (0-9). Default: 6'
    required: false
    default: '6'

runs:
  using: 'docker'
  image: 'Dockerfile'  # Uses the Dockerfile in the root of your repository
  env:
    INPUT_DIRECTORY: ${{ inputs.directory }}
    INPUT_ALGORITHMS: ${{ inputs.algorithms }}
    INPUT_BROTLI_LEVEL: ${{ inputs.brotli-level }}
    INPUT_GZIP_LEVEL: ${{ inputs.gzip-level }}
