name: 'DeploySlim'
description: 'Compress web assets (HTML, CSS, JS, etc.) with Brotli & Gzip in GitHub Actions.'
author: 'CornerstoneCode'

inputs:
  directory:
    description: 'The directory containing the web assets to compress.'
    required: false
    default: '.'
  algorithms:
    description: 'Comma-separated list of compression algorithms (br, gz). Default: br,gz'
    required: false
    default: 'br,gz'
  brotli-level:
    description: 'Brotli compression level (0-11). Default: 11'
    required: false
    default: '11'
  gzip-level:
    description: 'Gzip compression level (0-9). Default: 9'
    required: false
    default: '9'

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install brotli
      shell: bash

    - name: Run compression script
      run: python main.py
      shell: bash
      env:
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_ALGORITHMS: ${{ inputs.algorithms }}
        INPUT_BROTLI_LEVEL: ${{ inputs.brotli-level }}
        INPUT_GZIP_LEVEL: ${{ inputs.gzip-level }}